import type { Level, Question } from '../types/game';
import { SPELLS } from './spells';

const makeQuestion = (a: number, b: number, hintDouble?: number): Question => ({
  a,
  b,
  answer: a + b,
  ...(hintDouble !== undefined ? { hintDouble } : {}),
});

export const LEVELS: Level[] = [
  {
    id: 1,
    nameHe: 'שנה ראשונה — כפולות קלות',
    emoji: '🦉',
    questions: [
      makeQuestion(1, 1),
      makeQuestion(2, 2),
      makeQuestion(3, 3),
      makeQuestion(4, 4),
      makeQuestion(5, 5),
      makeQuestion(1, 1),
      makeQuestion(2, 2),
      makeQuestion(3, 3),
      makeQuestion(4, 4),
      makeQuestion(5, 5),
    ],
    passingScore: 80,
    spellReward: SPELLS.lumos,
    isNearDoubles: false,
  },
  {
    id: 2,
    nameHe: 'שנה שנייה — כפולות גבוהות',
    emoji: '📚',
    questions: [
      makeQuestion(6, 6),
      makeQuestion(7, 7),
      makeQuestion(8, 8),
      makeQuestion(9, 9),
      makeQuestion(10, 10),
      makeQuestion(6, 6),
      makeQuestion(7, 7),
      makeQuestion(8, 8),
      makeQuestion(9, 9),
      makeQuestion(10, 10),
    ],
    passingScore: 80,
    spellReward: SPELLS.wingardiumLeviosa,
    isNearDoubles: false,
  },
  {
    id: 3,
    nameHe: 'שנה שלישית — ערבוב כפולות',
    emoji: '🪄',
    questions: [
      makeQuestion(1, 1),
      makeQuestion(2, 2),
      makeQuestion(3, 3),
      makeQuestion(4, 4),
      makeQuestion(5, 5),
      makeQuestion(6, 6),
      makeQuestion(7, 7),
      makeQuestion(8, 8),
      makeQuestion(9, 9),
      makeQuestion(10, 10),
    ],
    passingScore: 80,
    spellReward: SPELLS.expectoPatronum,
    isNearDoubles: false,
  },
  {
    id: 4,
    nameHe: 'שנה רביעית — קרוב לכפולה',
    emoji: '🗺️',
    questions: [
      makeQuestion(4, 5, 4),
      makeQuestion(5, 6, 5),
      makeQuestion(6, 7, 6),
      makeQuestion(4, 5, 4),
      makeQuestion(5, 6, 5),
      makeQuestion(6, 7, 6),
      makeQuestion(4, 5, 4),
      makeQuestion(5, 6, 5),
      makeQuestion(6, 7, 6),
      makeQuestion(5, 6, 5),
    ],
    passingScore: 80,
    spellReward: SPELLS.maraudersMap,
    isNearDoubles: true,
  },
  {
    id: 5,
    nameHe: 'שנה חמישית — קרוב לכפולה מתקדם',
    emoji: '✨',
    questions: [
      makeQuestion(7, 8, 7),
      makeQuestion(8, 9, 8),
      makeQuestion(9, 10, 9),
      makeQuestion(7, 8, 7),
      makeQuestion(8, 9, 8),
      makeQuestion(9, 10, 9),
      makeQuestion(7, 8, 7),
      makeQuestion(8, 9, 8),
      makeQuestion(9, 10, 9),
      makeQuestion(8, 9, 8),
    ],
    passingScore: 80,
    spellReward: SPELLS.accio,
    isNearDoubles: true,
  },
  {
    id: 6,
    nameHe: 'בחינות סוף שנה — מבחן מיון סופי',
    emoji: '🏰',
    questions: [
      makeQuestion(2, 2),
      makeQuestion(5, 5),
      makeQuestion(8, 8),
      makeQuestion(10, 10),
      makeQuestion(4, 5),
      makeQuestion(6, 7),
      makeQuestion(7, 8),
      makeQuestion(8, 9),
      makeQuestion(9, 10),
      makeQuestion(3, 3),
    ],
    passingScore: 80,
    spellReward: SPELLS.houseCup,
    isNearDoubles: false,
  },
];

export const LEVELS_BY_ID: Record<number, Level> = Object.fromEntries(
  LEVELS.map((level) => [level.id, level]),
) as Record<number, Level>;
